Add functionality overview to interpreter module docstring.
kensho-technologies/graphql-compiler pull request #931
Opened 2020-09-24 16:15 UTC by obi1kenobi

Intended to be a basic intro to the purpose and structure of the interpreter module. We could perhaps reuse some or all of this in the ReadTheDocs description of the interpreter — thoughts?

2020-09-24 16:33 UTC, bojanserafimov commented
Looks good to me. You forgot the copyright header.

Once we're cofortable with having this in public docs the description of the compiler can change from "library that simplifies database querying and exploration" to "a schema indirection layer for arbitrary data sources" or something similar.

2020-09-24 17:19 UTC, obi1kenobi commented
I suppose technically the diff coverage _is_ 0% because nothing ever imports that file with no executable code in it. But also, as a vacuous truth, technically all executable code in the module I added _is_ executed in tests, so maybe the diff coverage is 100% instead 🤔

2020-09-24 21:02 UTC, branen requested changes
Looks good!  I suggested two small changes meant to make it more alluring to prospective users.

2020-09-24 21:02 UTC, branen commented on graphql_compiler/interpreter/__init__.py
> +logic is abstracted into the straightforward API of the InterpreterAdapter class, which should be
```suggestion
logic is abstracted into the straightforward, four-method API of the InterpreterAdapter class, which should be
```
Although you mention the compactness & simplicity of the API footprint below, I think it's worth mentioning here, too, as an enticement to the prospective user to keep reading.  (It is EXTREMELY enticing!)

2020-09-28 15:00 UTC, branen approved these changes

2020-09-28 15:25 UTC, merged