Add docstring for get_tokens_of_type().
kensho-technologies/graphql-compiler pull request #944
Opened 2020-10-06 21:36 UTC by obi1kenobi

2020-10-07 15:12 UTC, branen requested changes
Looks good!  I made a few suggestions that I think will make it slightly easier to read for naive users.

2020-10-07 15:12 UTC, branen commented on graphql_compiler/interpreter/typedefs.py
> +        uses those tokens to perform the rest of the query via the remaining API methods.
```suggestion
        uses those tokens to perform the rest of the query via the remaining interpreter API methods.
```
If the reader's thinking about how to implement an adapter over some other API, the clarification may help here.

2020-10-07 15:12 UTC, branen commented on graphql_compiler/interpreter/typedefs.py
> +            runtime_arg_hints: values of any runtime arguments provided to the query for use in
```suggestion
            runtime_arg_hints: names and values of any runtime arguments provided to the query for use in
```

2020-10-07 15:33 UTC, obi1kenobi commented
Thanks!

2020-10-07 19:05 UTC, chewselene commented on graphql_compiler/interpreter/typedefs.py
> +            used_property_hints: the property names of the requested vertices the that
typo: extra `the` (before the `that`)

2020-10-08 15:07 UTC, obi1kenobi commented on graphql_compiler/interpreter/typedefs.py
> +                               for use in filtering operations (e.g. "$foo").
Good point. Replaced with `$arg_name` everywhere to avoid this problem in other places as well.

2020-10-08 17:21 UTC, branen approved these changes

2020-10-09 01:15 UTC, merged